/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "primary-container": "#0077b6",
        "outline-variant": "#bfc7d1",
        "on-secondary-fixed-variant": "#004e5f",
        "on-surface-variant": "#404850",
        "surface-container-highest": "#e0e3e5",
        "surface-container-low": "#f2f4f6",
        "error-container": "#ffdad6",
        "on-surface": "#191c1e",
        "on-tertiary-fixed": "#001f24",
        "background": "#f7f9fb",
        "surface-container": "#eceef0",
        "primary-fixed": "#cde5ff",
        "tertiary-fixed-dim": "#a8cdd5",
        "surface-dim": "#d8dadc",
        "on-primary-container": "#f3f7ff",
        "surface-tint": "#006399",
        "secondary": "#00677d",
        "error": "#ba1a1a",
        "on-background": "#191c1e",
        "secondary-fixed-dim": "#4cd6fb",
        "on-primary-fixed-variant": "#004b74",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2d3133",
        "primary-fixed-dim": "#94ccff",
        "on-tertiary-container": "#e7fbff",
        "on-tertiary-fixed-variant": "#284c53",
        "on-primary": "#ffffff",
        "on-secondary-container": "#005c70",
        "inverse-on-surface": "#eff1f3",
        "surface-bright": "#f7f9fb",
        "tertiary-fixed": "#c3e9f1",
        "on-secondary-fixed": "#001f27",
        "tertiary-container": "#53777e",
        "secondary-container": "#50d9fe",
        "surface-container-high": "#e6e8ea",
        "inverse-primary": "#94ccff",
        "tertiary": "#3b5e65",
        "primary": "#005d90",
        "secondary-fixed": "#b3ebff",
        "surface-variant": "#e0e3e5",
        "outline": "#707881",
        "on-error-container": "#93000a",
        "surface": "#f7f9fb",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-fixed": "#001d32"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      }
    },
  },
  plugins: [],
}
